<?php require('template/header.phtml') ?>

<h3><b>Basket</b></h3>


<?php if ( isset( $_SESSION['selectedMovies'] ) && !empty($_SESSION['selectedMovies'])):?>
	<h4><b>Your movies:</b> </h4>
	<table class="table-bordered">
		<thead>
		<tr>
			<th>DVD details</th>
			<th>Price</th>
		</tr>
		</thead>
		<tbody>

		<?php foreach ($_SESSION['selectedMovies'] as $dvd) : $dvd=unserialize($dvd);?>
			<tr>
				<td>
					<p><?php echo $dvd->title;?> </p>
				</td>
				<td>&pound<?php echo $dvd->price;?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<p><h3>Total rental cost = &pound<?php echo $totalCost ?></h3></p>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
	<input type="submit" name="payAndLogout" value="Pay for DVD and Logout">
</form>

<?php else: ?>
<div class="text-info alert-warning">
	<h4><b>Your basket is empty.</b> </h4>
	You can add DVDs from <a href="allDVDs.php">here</a>
</div>
    <?php endif;?>
<?php require('template/footer.phtml') ?>
