<?php require('template/header.phtml') ?>

<h3><b>Basket</b></h3>


<?php if ( isset( $selectedMovies ) && !empty($selectedMovies)):?>
	<h4><b>Your movies:</b> </h4>
	<table class="table-bordered">
		<thead>
		<tr>
			<th>DVD details</th>
			<th>Price</th>
		</tr>
		</thead>
		<tbody>

		<?php foreach ($selectedMovies as $dvd) : ?>
			<tr>
				<td>
					<p><?php echo $dvd->title;?> </p>
				</td>
				<td>&pound<?php echo $dvd->price;?>
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<p><h3>Total rental cost = &pound<?php echo $totalCost ?></h3></p>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
	<input type="submit" name="payAndLogout" value="Pay for DVD and Logout">
</form>

<?php else: ?>
	<h4><b>Your basket is empty.</b> </h4>
<?php endif;?>
<?php require('template/footer.phtml') ?>
