<?php require('template/header.phtml') ?>

<h2><b>Filter by director</b> </h2>

<p>Director:
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
	<select name="director" class="input-sm">

		<?php foreach ($allDirectors as $director) : ?>
			<option <?php if (isset($_POST['director'])) {if ($_POST['director'] == $director["director"]) {?> selected <?php }} ?> value="<?php echo $director["director"] ?>"><?php echo $director["director"] ?></option>
		<?php endforeach; ?>
	</select>

	<input class="btn btn-primary" type="submit" name="directorSelect" value="Select">
</form>
</p>

<?php require('printDVDs.phtml') ?>
<?php require('template/footer.phtml') ?>
