<?php require('template/header.phtml') ?>

<h2><b>Filter by title</b> </h2>

<p>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
	<input class="input-sm" type="text" name="title" value="<?php if( isset($_POST['title'])) echo $_POST['title']  ?>">
	<input class="btn btn-primary" type="submit" name="titleSelect" value="Search">
</form>
</p>

<?php require('printCDs.phtml') ?>
<?php require('template/footer.phtml') ?>
