<?php require( 'template/header.phtml' );?>
<h3><b>Login</b></h3>
<p>If you have not already Registered, <u><a href="registration.php">Register here</a></u></p>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
	<p><b>Login</b> using your <b>email address</b> and password:<br>
		Email: <input type="email" name="email" value="<?php if(!empty($_POST['email']) && !isset( $_POST["reset"] ))echo $_POST['email']; ?>"><br>
		Password: <input type="password" name="password" value="<?php if(!empty($_POST['password']) && !isset( $_POST["reset"] ))echo $_POST['password']; ?>">
	</p>
	<p>
		<input class="btn btn-primary" type="submit" name="login" value="Login">
		<input class="btn btn-danger" type="submit" name="reset" value="Reset">
	</p>
</form>




<?php if(isset($view->messages))
foreach($view->messages as $message):?>
	<div class="alert-danger"> <?php echo $message ?></div>
<?php endforeach;
require( 'template/footer.phtml' ) ?>
