<?php if (isset($result) && is_array($result)): ?>
    <table class="table-bordered">
        <thead>
        <tr>
            <th>DVD details</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($result as $dvd): ?>
            <tr>
                <td>
                    <?php
                    $images = explode(", ", $dvd['image']);
                    foreach($images as $image){
                        ?><img src="<?php echo $image;?>" height="250" width="170"><?php
                    }?>
                    <br>
                    <p>Title: <?php echo $dvd['title']; ?> (<?php echo $dvd['year']; ?>)</p>

                    <p>Writer: <?php echo $dvd['writer']; ?> </p>

                    <p>Artist: <?php echo $dvd['artist']; ?> </p>

                    <p>Genre: <?php echo $dvd['genre']; ?> </p>

                    <p>Synopsis: <?php echo $dvd['synopsis']; ?> </p>
                </td>
                <td>&pound<?php switch ($dvd['priceBand']) {
                        case "A":
                            echo "3.50";
                            break;
                        case "B":
                            echo "2.50";
                            break;
                        case "C":
                            echo "1.00";
                            break;
                    }?>
                    <br>

                    <?php if (is_null($dvd['clientRenting'])):?>
                        <a class="btn btn-primary" href="basket.php?id=<?php echo $dvd['id'] ?>">Rent</a>
                    <?php else: ?>
                        <a class="btn btn-warning">Rented out</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="alert-warning"> No results found.</div>
<?php endif; ?>
