<?php require( 'template/header.phtml' );

// show messages from registration if there are any.
if (isset($registration)) {
	if ($registration->messages) {
		foreach ($registration->messages as $message) {
			echo $message;
		}
	}
}
?>
<h3><b>Registration</b></h3>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
	<p>Enter your details:<br>
		Email: <input type="email" name="email" value="<?php if(!empty($_POST['email']) && !isset( $_POST["reset"] ))echo $_POST['email']; ?>"><br>
		Password: <input type="password" name="password" value="<?php if(!empty($_POST['password']) && !isset( $_POST["reset"] ))echo $_POST['password']; ?>"><br>
		Address: <input type="text" name="address" value="<?php if(!empty($_POST['address']) && !isset( $_POST["reset"] ))echo $_POST['address']; ?>"><br>
		mobile: <input type="tel" name="mobile" value="<?php if(!empty($_POST['mobile']) && !isset( $_POST["reset"] ))echo $_POST['mobile']; ?>"><br>
	</p>
	<p>
		<input type="submit" name="submit" value="Submit">
		<input type="submit" name="reset" value="Reset">
	</p>

</form>



<?php require( 'template/footer.phtml' ) ?>
