    </div>


    <div class-"row">
        <div id="footer" class="col-xs-12">
            <?php

            if(isset($_COOKIE["email"])) {?>
                <p>Logged in as :  <?php echo $_COOKIE["email"]?></p>
            <?php }else {
                echo "Not logged in.";
            }?>

        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>