</div>
</div>


<div>

        <div class="row col-xs-8 col-xs-offset-2">
            <p class="text-center">
                <?php
                if (session_status() == PHP_SESSION_NONE) {
                    session_start();
                }
                if(isset($_SESSION['email'])) {?>
            <p>Logged in as : <?php echo $_SESSION["email"]?> </p>
            <?php }else {
                echo "Not logged in.";
            }?>
            <p>
                Site created by <a href="mailto:P.I.Stanev@edu.salford.ac.uk">Petar Stanev</a>.
                <a href="http://www.salford.ac.uk/"> University of Salford</a>.
            </p>
        </div>

</div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>