<?php
error_reporting(E_ALL | E_STRICT);
ini_set('display_erorrs', true);
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}
//var_dump($_SESSION);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php echo $view->pageTitle; ?></title>
</head>

<body>

<div class="container">
        <div class="row page-header" id="header">
            <div id="title" class="col-xs-12">

                <img class="col-xs-2" src="images/logo.jpg" alt="Salford University" />

                    <div class="col-xs-9 text-center"> <h1><b><?php echo $view->pageTitle ?> </b></h1></div>

            </div>
        </div>

        <div class="row">
        <div id="menu" class="col-xs-12 col-sm-3 col-md-2">
            <ul class="nav nav-pills nav-stacked">
                <li><a href="index.php">Home</a></li>
                <li><a href="login.php">Login</a></li>
                <li><a href="allDVDs.php">Show all DVDs</a></li>
                <li><a href="filterByTitle.php">Filter by Title</a></li>
                <li><a href="filterByGenre.php">Filter by Genre</a></li>
                <li><a href="filterByDirector.php">Filter by Director</a></li>
                <li><a href="basket.php">Basket</a></li>
            </ul>
        </div>

    <div id="content" class="col-xs-12 col-sm-9 col-md-10">



